name = "cloudflare-temp-mail"
main = "src/worker.ts"
compatibility_date = "2026-04-10"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "cloudflare-temp-mail"
database_id = "resource-created-d1-id"

[[r2_buckets]]
binding = "MAIL_R2"
bucket_name = "cloudflare-temp-mail-data"

[[kv_namespaces]]
binding = "CACHE_KV"
id = "resource-created-kv-id"

[vars]
APP_NAME = "Lin Mail"
